import { test, expect } from "@playwright/test";

test("launch, stop, continue, archive, export and remove a branch task", async ({ page, request }) => {
  await page.goto("/");
  await page.getByRole("button", { name: /Workspaces$/ }).click();
  await page.getByRole("button", { name: "New session" }).click();
  await page.getByLabel("Durable workspace").selectOption({ label: "Clean project" });
  await expect(page.getByLabel("Working files")).toHaveValue("new_worktree");
  await page.getByLabel("Session name").fill("Browser task");
  await page.getByRole("button", { name: "Launch session", exact: true }).click();
  await expect(page.getByLabel("Session name")).toHaveCount(0);
  const sessions = await (await request.get("/api/v1/sessions")).json();
  const first = sessions.find((session: { name: string }) => session.name === "Browser task");
  expect(first.worktree_id).toBeTruthy();
  expect((await request.post(`/api/v1/sessions/${first.id}/actions`, { data: { action: "stop" } })).ok()).toBeTruthy();
  await page.reload();
  await page.getByRole("button", { name: /Workspaces$/ }).click();
  const card = page.locator(".workspace-card").filter({ has: page.getByRole("heading", { name: "Clean project", exact: true }) });
  await card.getByRole("button", { name: "Continue task…" }).click();
  await expect(page.getByLabel("Working files")).toHaveValue("existing_worktree");
  await page.getByLabel("Session name").fill("Browser continuation");
  await page.getByRole("button", { name: "Launch session", exact: true }).click();
  await expect(page.getByLabel("Session name")).toHaveCount(0);
  const continued = (await (await request.get("/api/v1/sessions")).json()).find((session: { name: string }) => session.name === "Browser continuation");
  expect(continued.worktree_id).toBe(first.worktree_id);
  expect((await request.post(`/api/v1/sessions/${continued.id}/actions`, { data: { action: "stop" } })).ok()).toBeTruthy();
  for (const id of [first.id, continued.id]) expect((await request.delete(`/api/v1/sessions/${id}`)).ok()).toBeTruthy();
  await page.reload();
  await page.getByRole("button", { name: /Workspaces$/ }).click();
  await card.getByRole("button", { name: "Archive", exact: true }).click();
  await card.getByRole("button", { name: "Restore task", exact: true }).click();
  await card.getByRole("button", { name: "Export branch…" }).click();
  await expect(page.getByRole("alertdialog", { name: "Export branch" })).toContainText("does not merge");
  await page.getByRole("button", { name: "Export reviewed commit" }).click();
  await expect(card.locator(".branch-task small")).toContainText("exported");
  await card.getByRole("button", { name: "Remove checkout…" }).click();
  await page.getByRole("button", { name: "Remove clean checkout" }).click();
  await expect(card.locator(".branch-task small")).toContainText("removed");
  await card.getByRole("button", { name: "Refresh status" }).click();
  await card.getByRole("button", { name: "Export branch…" }).click();
  await expect(page.getByRole("button", { name: "Export reviewed commit" })).toBeEnabled();
  await page.getByRole("button", { name: "Export reviewed commit" }).click();
  await expect(page.getByRole("alertdialog", { name: "Export branch" })).toHaveCount(0);
  await card.getByRole("button", { name: "Delete workspace…" }).click();
  const deletion = page.getByRole("dialog", { name: "Delete Clean project?" });
  await deletion.getByRole("button", { name: "Permanently delete", exact: true }).click();
  await expect(deletion.getByText("Explicitly confirm deleting task history.", { exact: false })).toBeVisible();
  await deletion.getByRole("checkbox", { name: "Also permanently delete retained task branch history.", exact: false }).check();
  await deletion.getByRole("button", { name: "Permanently delete", exact: true }).click();
  await expect(page.getByRole("heading", { name: "Clean project", exact: true })).toHaveCount(0);
});

test("dirty repositories require acknowledgement; plain folders use original files", async ({ page }) => {
  await page.goto("/");
  await page.getByRole("button", { name: /Workspaces$/ }).click();
  await page.getByRole("button", { name: "New session" }).click();
  await page.getByLabel("Durable workspace").selectOption({ label: "Dirty project" });
  await page.getByLabel("Session name").fill("Committed files only");
  await expect(page.getByLabel("Use committed version.", { exact: false })).toBeVisible();
  await page.getByRole("button", { name: "Launch session", exact: true }).click();
  await expect(page.getByLabel("Session name")).toBeVisible();
  await page.getByLabel("Use committed version.", { exact: false }).check();
  await page.getByRole("button", { name: "Launch session", exact: true }).click();
  await expect(page.getByLabel("Session name")).toHaveCount(0);
  await page.getByRole("button", { name: /Workspaces$/ }).click();
  await page.getByRole("button", { name: "New session" }).click();
  await page.getByLabel("Durable workspace").selectOption({ label: "Plain folder" });
  await expect(page.getByLabel("Working files")).toHaveValue("shared");
  await expect(page.getByText("Separate branches require a Git repository", { exact: false })).toBeVisible();
});
